force-app/main/default/objects/csvUploader_Mapping__mdt/csvUploader_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>csvUploader Mapping</label>
    <pluralLabel>csvUploader Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/csvUploader_Mapping__mdt/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <description>Apex Class to call after DML operation</description>
    <inlineHelpText>Apex Class to call after DML operation</inlineHelpText>
    <label>ApexClass</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/csvUploader_Mapping__mdt/fields/ApexMethod__c.field-meta.xml
<CustomField>
    <fullName>ApexMethod__c</fullName>
    <description>Apex Method to call after DML operation</description>
    <inlineHelpText>Apex Method to call after DML operation</inlineHelpText>
    <label>ApexMethod</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/csvUploader_Mapping__mdt/fields/DML_Type__c.field-meta.xml
<CustomField>
    <fullName>DML_Type__c</fullName>
    <label>DML Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Insert</fullName>
                <default>true</default>
                <label>Insert</label>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Upsert</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/csvUploader_Mapping__mdt/fields/ExternalIdFieldAPI__c.field-meta.xml
<CustomField>
    <fullName>ExternalIdFieldAPI__c</fullName>
    <description>The API name of the field to use for Updating or Upserting these records</description>
    <label>External Id Field API</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/csvUploader_Mapping__mdt/fields/Help_Text__c.field-meta.xml
<CustomField>
    <fullName>Help_Text__c</fullName>
    <label>Help Text</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/csvUploader_Mapping__mdt/fields/Mapping__c.field-meta.xml
<CustomField>
    <fullName>Mapping__c</fullName>
    <description>JSON formatted Mapping from file to sf field</description>
    <label>Mapping</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/csvUploader_Mapping__mdt/fields/ObjectAPI__c.field-meta.xml
<CustomField>
    <fullName>ObjectAPI__c</fullName>
    <label>Object API Name</label>
    <length>35</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/csvUploader_Mapping__mdt/fields/Synchronous_Limit__c.field-meta.xml
<CustomField>
    <fullName>Synchronous_Limit__c</fullName>
    <defaultValue>500</defaultValue>
    <label>Synchronous Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/csvUploader_Mapping__mdt/fields/Template_Url__c.field-meta.xml
<CustomField>
    <fullName>Template_Url__c</fullName>
    <label>Template Url</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/csvUploaderHelper.cls
public without sharing class csvUploaderHelper extends VisualEditor.DynamicPickList{
    
    @AuraEnabled
    public static List<csvUploader_Mapping__mdt> getSavedMDMappings() {
        return [SELECT MasterLabel,DeveloperName,Synchronous_Limit__c,Help_Text__c,Template_Url__c,
                DML_Type__c,ExternalIdFieldAPI__c,Mapping__c,ObjectAPI__c,ApexClass__c,ApexMethod__c 
                FROM csvUploader_Mapping__mdt];
    }
    @AuraEnabled
    public static String dbBatchDML(List <sObject> sObjects,string dmlType) {
        DynamicBatchClass_Batch batch = new DynamicBatchClass_Batch(sObjects, dmlType);
        batch.triggeringProcessName='CSVUploader';
        batch.notifyOnCompletion=true;
        system.scheduleBatch(batch, 'CSVUploader '+UserInfo.getName(), 0);
        return 'Success';
    }
    @AuraEnabled
    public static String dbBatchUpdateWExternalKey(List <sObject> sObjects,String fieldAPI,String objectAPI,Boolean onBatchCompletionCallOtherApex,String otherApexClassName,String otherApexMethodName) {
        DynamicBatchClass_Batch batch = new DynamicBatchClass_Batch(sObjects, 'updateExternal');
        batch.triggeringProcessName='CSVUploader';
        batch.notifyOnCompletion=true;
        batch.objectAPI=objectAPI;
        batch.fieldAPI=fieldAPI;
        batch.onBatchCompletionCallOtherApex=onBatchCompletionCallOtherApex;
        batch.otherApexClassName=otherApexClassName;
        batch.otherApexMethodName=otherApexMethodName;
        system.scheduleBatch(batch, 'CSVUploader '+UserInfo.getName(), 0);
        return 'Success';
    }

    public override VisualEditor.DynamicPickListRows getValues() {
        VisualEditor.DynamicPickListRows  myValues = new VisualEditor.DynamicPickListRows();
        for(csvUploader_Mapping__mdt data:[SELECT MasterLabel,DeveloperName,Synchronous_Limit__c,Template_Url__c,
                DML_Type__c,ExternalIdFieldAPI__c,Mapping__c,ObjectAPI__c,Help_Text__c 
                FROM csvUploader_Mapping__mdt])
        {
            VisualEditor.DataRow value1 = new VisualEditor.DataRow(data.MasterLabel,data.DeveloperName);
            myValues.addRow(value1);
        }
        return myValues;
    }
    public override VisualEditor.DataRow getDefaultValue(){
        VisualEditor.DataRow defaultValue = new VisualEditor.DataRow(null, null);
        return defaultValue;
    }
}